name: $(major).$(minor).$(Rev:r)
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Agent'
    exclude:
      - 'Agent/azure-pipelines.yml'
pool:
  name: 'SelfHostedAgentPoolNameHere'
variables:
  - name: buildConfiguration
    value: 'Release'
  - name: major
    value: 1
  - name: minor
    value: 0
  - name: workingDirectory
    value: 'Agent'
  - name: ContainerRegistry
    value: 'Container Registry Service Connection Name Here'
  - name: KubernetesServiceConnectionNonProd
    value: 'Kubernetes Service Connection Name Here'
  - name: KubernetesServiceConnectionProd
    value: 'Kubernetes Service Connection Name Here'
  - name: NonProdEnvironmentName
    value: nonprod
  - name: ProdEnvironmentName
    value: prod
stages:
  - stage: build
    displayName: 'Build And Push Image'
    jobs:
      - job: build
        displayName: 'Build and Push Image'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: $(ContainerRegistry)
              repository: 'linuxagent'
              command: buildAndPush
              Dockerfile: '$(workingDirectory)/Dockerfile'
              buildContext: '$(workingDirectory)'
              tags: |
                $(Build.BuildNumber)
              addPipelineData: true
      - job: publish
        displayName: Publish
        steps:
          - task: PublishPipelineArtifact@1
            displayName: 'Publish k8s'
            inputs:
              artifact: config
              targetPath: '$(workingDirectory)/agent-spec.yaml'
  - stage: deployNonProd
    displayName: 'Deploy Controller Non Production'
    jobs:
      - deployment: deploy
        displayName: 'Deploy'
        environment: $(NonProdEnvironmentName)
        strategy:
         runOnce:
           deploy:
             steps:
              - download: current
                artifact: config
              - task: replacetokens@3
                displayName: 'Update Config'
                inputs:
                  rootDirectory: '$(Pipeline.Workspace)/config'
                  targetFiles: '**/*.yaml'
                  encoding: 'auto'
                  writeBOM: true
                  actionOnMissing: 'fail'
                  keepToken: false
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'
              - task: Kubernetes@1
                displayName: 'Kubectl Apply AgentSpec'
                inputs:
                  connectionType: 'Kubernetes Service Connection'
                  kubernetesServiceEndpoint: $(KubernetesServiceConnectionNonProd)
                  command: 'apply'
                  useConfigurationFile: true
                  configuration: '$(Pipeline.Workspace)/config/agent-spec.yaml'
                  secretType: 'generic'
                  forceUpdate: false
                  workingDirectory: '$(Pipeline.Workspace)/config/'
                  outputFormat: 'none'
  - stage: deployProd
    displayName: 'Deploy Controller Production'
    jobs:
      - deployment: deploy
        displayName: 'Deploy'
        environment: $(ProdEnvironmentName)
        strategy:
         runOnce:
           deploy:
             steps:
              - download: current
                artifact: config
              - task: replacetokens@3
                displayName: 'Update Config'
                inputs:
                  rootDirectory: '$(Pipeline.Workspace)/config'
                  targetFiles: '**/*.yaml'
                  encoding: 'auto'
                  writeBOM: true
                  actionOnMissing: 'fail'
                  keepToken: false
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'
              - task: Kubernetes@1
                displayName: 'Kubectl Apply AgentSpec'
                inputs:
                  connectionType: 'Kubernetes Service Connection'
                  kubernetesServiceEndpoint: $(KubernetesServiceConnectionProd)
                  command: 'apply'
                  useConfigurationFile: true
                  configuration: '$(Pipeline.Workspace)/config/agent-spec.yaml'
                  secretType: 'generic'
                  forceUpdate: false
                  workingDirectory: '$(Pipeline.Workspace)/config/'
                  outputFormat: 'none'